# Generated by Django 5.1.5 on 2025-05-30 12:47

import django.contrib.postgres.search
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название"
                    ),
                ),
            ],
            options={
                "verbose_name": "Город",
                "verbose_name_plural": "Города",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PickupPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        max_length=255,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                5, message="Адрес должен содержать не менее 5 символов"
                            )
                        ],
                        verbose_name="Адрес",
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Район"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        blank=True, null=True, verbose_name="Поисковый вектор"
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pickup_points",
                        to="delivery.city",
                        verbose_name="Город",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пункт выдачи",
                "verbose_name_plural": "Пункты выдачи",
                "indexes": [
                    models.Index(
                        fields=["city", "is_active"],
                        name="delivery_pi_city_id_b95534_idx",
                    ),
                    models.Index(
                        fields=["search_vector"], name="delivery_pi_search__3dc35b_idx"
                    ),
                    models.Index(
                        fields=["district"], name="delivery_pi_distric_22502e_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("city", "address"), name="unique_city_address"
                    )
                ],
            },
        ),
    ]
