# Generated by Django 5.1.5 on 2025-05-14 20:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(5, message='Адрес должен содержать не менее 5 символов')], verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='pickuppoint',
            name='address',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(5, message='Адрес должен содержать не менее 5 символов')], verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='pickuppoint',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_points', to='delivery.city', verbose_name='Город'),
        ),
    ]
