# Generated by Django 5.1.5 on 2025-05-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_delivery_address_alter_pickuppoint_address_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pickuppoint',
            constraint=models.UniqueConstraint(fields=('city', 'address'), name='unique_city_address'),
        ),
    ]
