# Generated by Django 5.1.5 on 2025-05-16 18:15

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_pickuppoint_unique_city_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuppoint',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True, verbose_name='Поисковый вектор'),
        ),
        migrations.AddIndex(
            model_name='pickuppoint',
            index=models.Index(fields=['search_vector'], name='delivery_pi_search__3dc35b_idx'),
        ),
    ]
