# Generated by Django 5.1.5 on 2025-05-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_pickuppoint_search_vector_and_more'),
        ('orders', '0010_remove_order_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuppoint',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Район'),
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
    ]
