# Generated by Django 5.1.5 on 2025-05-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_pickuppoint_district_delete_delivery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.RemoveIndex(
            model_name='city',
            name='delivery_ci_name_8ff939_idx',
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AddIndex(
            model_name='pickuppoint',
            index=models.Index(fields=['district'], name='delivery_pi_distric_22502e_idx'),
        ),
    ]
