# Generated by Django 5.1.5 on 2025-03-07 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_product_category',
        ),
    ]
