# Generated by Django 5.1.5 on 2025-03-07 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_unique_product_category'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_product_category',
        ),
    ]
