# Generated by Django 5.1.5 on 2025-05-09 13:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_products_pr_discoun_0fa1d1_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='popularity_score',
            field=models.FloatField(default=0.0, verbose_name='Популярность'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['popularity_score'], name='products_pr_popular_26b74b_idx'),
        ),
    ]
