"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from datetime import timedelta
from pathlib import Path
import sys


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = str(os.environ.get('SECRET_KEY'))

# Определяем окружение
ENVIRONMENT = str(os.environ.get('ENVIRONMENT', 'development'))

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = ENVIRONMENT != 'production'

if ENVIRONMENT == 'production':
    ALLOWED_HOSTS = [
        'marketplace.example.com',  # Замените на реальный домен
        'www.marketplace.example.com',
        'api.marketplace.example.com',
    ]
else:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0']

# Application definition

INSTALLED_APPS = [
    'django_prometheus',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Импорты
    'rest_framework',
    'drf_spectacular',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'django_elasticsearch_dsl',
    # Приложения
    'apps.core.apps.CoreConfig',
    'apps.users.apps.UsersConfig',
    'apps.products.apps.ProductsConfig',
    'apps.reviews.apps.ReviewsConfig',
    'apps.comments.apps.CommentsConfig',
    'apps.orders.apps.OrdersConfig',
    'apps.carts.apps.CartsConfig',
    'apps.wishlists.apps.WishlistsConfig',
    'apps.delivery.apps.DeliveryConfig',
]

if DEBUG:
    INSTALLED_APPS += ['debug_toolbar']

MIDDLEWARE = [
    'django_prometheus.middleware.PrometheusBeforeMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Кастомные middleware для безопасности
    'apps.core.middleware.SecurityHeadersMiddleware',
    'apps.core.middleware.RateLimitMiddleware',
    'apps.core.middleware.RequestLoggingMiddleware',
    'apps.core.middleware.SQLInjectionProtectionMiddleware',
    'apps.core.middleware.HealthCheckMiddleware',
    'django_prometheus.middleware.PrometheusAfterMiddleware',
]

# Добавляем debug toolbar только в development
if DEBUG:
    MIDDLEWARE.append('debug_toolbar.middleware.DebugToolbarMiddleware')

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': str(os.environ.get('DB_ENGINE')),
        'NAME': str(os.environ.get('DB_NAME')),
        'USER': str(os.environ.get('DB_USER')),
        'PASSWORD': str(os.environ.get('DB_PASS')),
        'HOST': str(os.environ.get('DB_HOST')),
        'PORT': str(os.environ.get('DB_PORT')),
        'TEST': {
            'NAME': 'marketplace_test',  # Фиксированное имя тестовой базы
            'SERIALIZE': False,  # Отключаем сериализацию данных для ускорения тестов
        },
        'OPTIONS': {
            'connect_timeout': 10,
            'application_name': 'marketplace',
        },
    }
}

# Настройки для тестов
if 'test' in sys.argv:
    TESTING = True
    # Отключаем Elasticsearch для тестов
    ELASTICSEARCH_DSL = {
        'default': {
            'hosts': None
        }
    }
    # Отключаем Debug Toolbar для тестов
    INSTALLED_APPS = [app for app in INSTALLED_APPS if app != 'debug_toolbar']
    MIDDLEWARE = [m for m in MIDDLEWARE if m != 'debug_toolbar.middleware.DebugToolbarMiddleware']

    # Настройки REST framework для тестов
    REST_FRAMEWORK = {
        'DEFAULT_AUTHENTICATION_CLASSES': [
            'rest_framework.authentication.SessionAuthentication',
            'rest_framework.authentication.BasicAuthentication',
        ],
        'DEFAULT_PERMISSION_CLASSES': [
            'rest_framework.permissions.AllowAny',
        ],
        'TEST_REQUEST_DEFAULT_FORMAT': 'json'
    }
else:
    TESTING = False

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

INTERNAL_IPS = ['127.0.0.1']

DEBUG_TOOLBAR_CONFIG = {
    "SHOW_TOOLBAR_CALLBACK": lambda request: DEBUG,
}

STATIC_URL = '/static/'
STATIC_ROOT = (BASE_DIR / 'static')
STATICFILES_DIRS = [BASE_DIR / 'templates/js/']

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Конфигурация сервера электронной почты
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = str(os.environ.get('EMAIL_HOST_USER'))
EMAIL_HOST_PASSWORD = str(os.environ.get('EMAIL_HOST_PASSWORD'))
EMAIL_PORT = 587
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# CORS настройки
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "https://marketplace.example.com",  # Замените на реальный домен
    "https://www.marketplace.example.com",
]

CORS_ALLOW_CREDENTIALS = True
FRONTEND_URL = str(os.environ.get('FRONTEND_URL', "http://localhost:8000"))

# JWT настройки
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=14),
    'BLACKLIST_AFTER_ROTATION': True,
    'TOKEN_USER_CLASS': 'apps.users.authentication.CustomTokenUser',
    'ROTATE_REFRESH_TOKENS': True,

    # custom
    "AUTH_COOKIE": "access_token",  # имя cookie
    "REFRESH_COOKIE": "refresh_token",
    "AUTH_COOKIE_DOMAIN": None,  # указывает домен, для которого будет отправлен cookie
    "AUTH_COOKIE_SECURE": not DEBUG,  # ограничивает передачу cookie только через защищенные (HTTPS) соединения.
    "AUTH_COOKIE_HTTP_ONLY": True,  # запрещает клиентскому js доступ к cookie
    "AUTH_COOKIE_PATH": "/",  # URL-путь, по которому будет отправлен cookie
    "AUTH_COOKIE_SAMESITE": "Lax",  # указывает, следует ли отправлять cookie в межсайтовых запросах
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'apps.users.authentication.CustomJWTAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PERMISSION_CLASSES': [],  # Пустой список!

    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.AnonRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'user': '100/minute',  # 100 запросов в минуту для аутентифицированных
        'anon': '20/minute',  # 20 запросов в минуту для анонимных
        'verification_code': '5/hour',  # 5 запросов в час для кода подтверждения
    },
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Marketplace',
    'DESCRIPTION': 'Marketplace Documentation',
    'VERSION': '0.1.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

# Настройки Redis
REDIS_HOST = str(os.environ.get('REDIS_HOST', 'localhost'))
REDIS_PORT = str(os.environ.get('REDIS_PORT', '6379'))
REDIS_PASSWORD = str(os.environ.get('REDIS_PASSWORD', ''))

REDIS_URL = f"redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}" if REDIS_PASSWORD \
    else f"redis://{REDIS_HOST}:{REDIS_PORT}"

# Настройки кэширования
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': f'{REDIS_URL}/1',
        'KEY_PREFIX': 'marketplace',
        'TIMEOUT': 300,  # 5 минут по умолчанию
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'SOCKET_CONNECT_TIMEOUT': 5,
            'SOCKET_TIMEOUT': 5,
            'RETRY_ON_TIMEOUT': True,
            'MAX_CONNECTIONS': 50,
            'HEALTH_CHECK_INTERVAL': 30,
        }
    }
}

# Настройки сессий
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'default'
SESSION_COOKIE_AGE = 86400  # 24 часа
SESSION_COOKIE_NAME = 'marketplace_sessionid'

# Настройки Celery
RABBITMQ_HOST = str(os.environ.get('RABBITMQ_HOST', 'localhost'))
RABBITMQ_USER = str(os.environ.get('RABBITMQ_USER', 'guest'))
RABBITMQ_PASS = str(os.environ.get('RABBITMQ_PASS', ''))

CELERY_BROKER_URL = f'amqp://{RABBITMQ_USER}:{RABBITMQ_PASS}@{RABBITMQ_HOST}:5672//'
CELERY_RESULT_BACKEND = f'redis://{REDIS_HOST}:{REDIS_PORT}/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60
CELERY_WORKER_SEND_TASK_EVENTS = True

# Настройки Elasticsearch
ELASTICSEARCH_DSL = {
    'default': {
        'hosts': str(os.environ.get('ELASTICSEARCH_HOSTS')),
        'timeout': 30,
    },
}

# Дополнительные настройки Elasticsearch
ELASTICSEARCH_INDEX_NAMES = {
    'apps.delivery.documents.pickup_point': 'pickup_points',
    'apps.products.documents.product': 'products',
}

# Безопасность для продакшена
if ENVIRONMENT == 'production':
    # HTTPS настройки
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_HSTS_SECONDS = 31536000  # 1 год
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Cookie настройки
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SIMPLE_JWT['AUTH_COOKIE_SECURE'] = True

    # Security Headers
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'

    # Rate limiting для продакшена
    REST_FRAMEWORK['DEFAULT_THROTTLE_RATES'] = {
        'user': '1000/minute',  # 1000 запросов в минуту для аутентифицированных
        'anon': '100/minute',  # 100 запросов в минуту для анонимных
        'verification_code': '5/hour',  # 5 запросов в час для кода подтверждения
        'login': '5/minute',  # 5 попыток входа в минуту
        'register': '3/hour',  # 3 регистрации в час
    }

# Настройки логирования
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[%(asctime)s] %(levelname)s %(name)s: %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S'
        },
        'django.server': {
            'format': ' %(message)s',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO' if ENVIRONMENT == 'production' else 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'django.server': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'django.server',
        },
        'file': {
            'level': 'INFO' if ENVIRONMENT == 'production' else 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': 'logs/app.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.server': {
            'handlers': ['django.server'],
            'level': 'INFO',
            'propagate': False,
        },
        'apps': {
            'handlers': ['console', 'file'],
            'level': 'INFO' if ENVIRONMENT == 'production' else 'DEBUG',
            'propagate': True,
        },
        'security': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',
            'propagate': True,
        },
    }
}

# Создание директории для логов, если её нет
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)
