# Generated by Django 5.1.5 on 2025-02-17 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
