# Generated by Django 5.1.5 on 2025-04-09 17:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_product_unique_product_category'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rating',
            new_name='Review',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='reviews_rev_create__c6f2db_idx',
            old_name='reviews_rat_create__51e0b7_idx',
        ),
    ]
