# Generated by Django 5.1.5 on 2025-04-10 13:57

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_product_unique_product_category'),
        ('reviews', '0003_alter_review_options_alter_review_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='reviews_rev_create__c6f2db_idx',
        ),
        migrations.RemoveField(
            model_name='review',
            name='create_time',
        ),
        migrations.AddField(
            model_name='review',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.BigIntegerField(choices=[()], default=0, verbose_name='Оценка'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['-created', 'value'], name='reviews_rev_created_ef034a_idx'),
        ),
    ]
