# Generated by Django 5.1.5 on 2025-04-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_review_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст отзыва'),
        ),
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.BigIntegerField(choices=[()], default=0, verbose_name='Оценка'),
        ),
    ]
