# Generated by Django 5.1.5 on 2025-04-12 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_alter_review_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='ip_address',
        ),
    ]
