# Generated by Django 5.1.5 on 2025-04-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_alter_comment_user_alter_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Время создания записи.', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Время последнего обновления записи.', verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Время создания записи.', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Время последнего обновления записи.', verbose_name='Дата обновления'),
        ),
    ]
