global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'django-backend'
    scheme: http
    metrics_path: /metrics
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['nginx:80'] # Prometheus будет обращаться к сервису 'nginx' по порту 80