# Generated by Django 5.1.5 on 2025-05-30 12:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                        verbose_name="Количество",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="orders.order",
                        verbose_name="Заказ",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="products.product",
                        verbose_name="Товар",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Предмет заказа/корзины",
                "verbose_name_plural": "Предметы заказа/корзины",
                "indexes": [
                    models.Index(fields=["user", "product"], name="idx_user_product"),
                    models.Index(fields=["order", "product"], name="idx_order_product"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("order__isnull", True)),
                        fields=("user", "product"),
                        name="unique_cart_product",
                        violation_error_message="Товар уже находится в корзине пользователя.",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("order__isnull", False)),
                        fields=("order", "product"),
                        name="unique_order_product",
                        violation_error_message="Товар уже включен в заказ.",
                    ),
                ],
            },
        ),
    ]
