# Generated by Django 5.1.5 on 2025-04-24 20:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_alter_orderitem_quantity'),
        ('orders', '0007_alter_order_status'),
        ('products', '0010_remove_product_unique_product_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='orderitem',
            name='unique_cart_product',
        ),
        migrations.RemoveConstraint(
            model_name='orderitem',
            name='unique_order_product',
        ),
        migrations.RenameIndex(
            model_name='orderitem',
            new_name='idx_user_product',
            old_name='carts_order_user_id_fb6e63_idx',
        ),
        migrations.RenameIndex(
            model_name='orderitem',
            new_name='idx_order_product',
            old_name='carts_order_order_i_8cc303_idx',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(condition=models.Q(('order__isnull', True)), fields=('user', 'product'), name='unique_cart_product', violation_error_message='Товар уже находится в корзине пользователя.'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(condition=models.Q(('order__isnull', False)), fields=('order', 'product'), name='unique_order_product', violation_error_message='Товар уже включен в заказ.'),
        ),
    ]
