# Generated by Django 5.1.5 on 2025-04-27 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentLike',
        ),
    ]
