# Generated by Django 5.1.5 on 2025-03-12 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
