# Generated by Django 5.1.5 on 2025-03-21 18:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_delivery_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'Адрес доставки', 'verbose_name_plural': 'Адреса доставки'},
        ),
        migrations.AddField(
            model_name='delivery',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='delivery',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['user', 'is_primary'], name='orders_deli_user_id_eae7b6_idx'),
        ),
    ]
