# Generated by Django 5.1.5 on 2025-05-21 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_delivery_user_alter_order_delivery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery',
        ),
    ]
