# Generated by Django 5.1.5 on 2025-05-22 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_pickuppoint_district_delete_delivery'),
        ('orders', '0011_remove_order_either_delivery_or_pickup_point_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='either_pickup_point',
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='delivery.pickuppoint', verbose_name='Пункт выдачи'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('pickup_point__is_active', True)), name='active_pickup_point'),
        ),
    ]
