# Generated by Django 5.1.5 on 2025-05-22 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_remove_order_either_pickup_point_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='active_pickup_point',
        ),
    ]
