# Generated by Django 5.1.5 on 2025-04-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitem',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Время создания записи.', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Время последнего обновления записи.', verbose_name='Дата обновления'),
        ),
    ]
