# Generated by Django 5.1.5 on 2025-05-02 14:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverified',
            name='code_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время создания кода'),
        ),
        migrations.AlterField(
            model_name='emailverified',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Код подтверждения'),
        ),
        migrations.AlterField(
            model_name='emailverified',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_verified', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+\\d{9}$|^\\+\\d \\(\\d{3}\\) \\d{3}-\\d{2}-\\d{2}$', message="Номер телефона должен соответствовать шаблону: '+999999999' или '+9 (999) 999-99-99'.")], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='public_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Публичный идентификатор'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='emailverified',
            index=models.Index(fields=['code_created_at'], name='users_email_code_cr_b296f4_idx'),
        ),
    ]
