# Generated by Django 5.1.5 on 2025-05-08 17:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_emailverified_code_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userprofile',
            name='users_userp_public__ca76cd_idx',
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['public_id'], name='users_userp_public__afe67f_idx'),
        ),
    ]
