# Generated by Django 5.1.5 on 2025-02-04 17:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_userprofile_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['user__id'], 'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['public_id', 'id'], name='users_userp_public__ca76cd_idx'),
        ),
    ]
