# Generated by Django 5.1.5 on 2025-02-05 18:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='images/avatars/default.png', upload_to='images/avatars/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'])], verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('\\+?1?\\d{9,15} | \\+\\d \\(\\d{3}\\) \\d{3}-\\d{2}-\\d{2}', message="Номер телефона должен соответствовать шаблону: '+999999999'.")]),
        ),
    ]
