# Generated by Django 5.1.5 on 2025-02-05 18:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+\\d{9}$|^\\+\\d \\(\\d{3}\\) \\d{3}-\\d{2}-\\d{2}$', message="Номер телефона должен соответствовать шаблону: '+999999999' или +'9 (999) 999-99-99'.")]),
        ),
    ]
