# Generated by Django 5.1.5 on 2025-02-14 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_emailverified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailverified',
            options={'ordering': ['code_created_at'], 'verbose_name': 'Проверка почты', 'verbose_name_plural': 'Проверка почты'},
        ),
    ]
